# Generated by Django 4.0.2 on 2022-03-04 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_mapimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapimage',
            name='map_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
